@hostname=localhost:8888
# @hostname=chabotprime-api.chabot.kr:8888

###
GET http://{{hostname}}/api/nice-auth?success-url=https%3A%2F%2Fgoogle.com&fail-url=https%3A%2F%2Fgoogle.com HTTP/1.1 

###
GET http://{{hostname}}/api/nice-auth/session?success-url=https%3A%2F%2Fgoogle.com&fail-url=https%3A%2F%2Fgoogle.com HTTP/1.1 

###
GET http://{{hostname}}/api/nice-auth/user-info?EncodeData=AgAFQlQ1NTRjMz61zHh7vhjITgVs0JMKYFappIWE%2BqC11t4Tdh9IwFz0JyGQ2G8sfu4w8%2BMBMEf%2BdRCQmePcNrn5WiCsMm5MQWvyHPpx2C53kvWcGGoucA07MtCDtK8VaXQAG%2BOf7x/GH02VVSe2sYA2IwO4A53DN4MXbGsQqhRlT0M/kvjD1J9EjdlDDUAR3sVRFVynxvH1ZARORhNQSiUPdP/9%2BDIRZDsTmRzZtgp5FBIcTULixGwI9o1mlu8z5jjGT3DYapIh7VDrynVzwNyaJeW477g6AlfofBGEMfoJ2zypfkumGSzvvU%2B5AE9FISZjQArwwIYtgzahdcy4RxPS/gZLTzgkiolz1VmUJIZs9a4D%2BqZJNEqYUfXF%2B740ymEBRABXXv2eGrNOMq1LYN3hxtMI8bmHPoEJEz0fjpUGFlfVB8C%2BUoO3zt3Ti2HFWRh/cj%2B03i8qOpXezd9etOj05gkR1k38EBKh8HIEbwsdKVsH/Uc2xMQhB9tGRCCa3TJRX7QV8qCKe6/8dI92qd0Mwo5ue1woGeVQ%2BPUDpw9AbepcPPlAPwxCtZJEG9puuNE1b1FxaqBM5qgpoAeAOdK%2BRZwz8TTJBDLR%2B%2BB%2BNBJS61mfhb%2BRWrrHFLRYewRXzQhhL%2B4u2g369mdSgrKzI30d6/65%2BQZAktEqU/VrdoK2FIVe1FjgzYXr9ICE0ni5iWvQqpR/VhfwDSnOzIL6gGru4d6Nr/T%2B HTTP/1.1



### form ftt
POST http://{{hostname}}/api/nice-auth/user-info HTTP/1.1 
Content-Type: application/x-www-form-urlencoded

EncodeData=AgAFQlQ1NTT95iv4FUMj5wJcft2FzGLyX7TQBQ4Tl0muftLdy88QwFz0JyGQ2G8sfu4w8+MBMEf+dRCQmePcNrn5WiCsMm5MdrI9X+GJKT7S0RYbShCZ5hEA3UeMLQ3wTFCvhr+QOUcKWmAsO1+Xatv9HddN95OX/WjkRbjZi4cniAhZQ9dsyxwtRP5/Ty5n3xLzqRzqkfiZQ+2uSa/TWXojqLLqhT8CWPja6U/BKfGnzBXPWu+hoJiXMFG26yF+6pTNE0prtUa2NUgN3qY5K2oEYcYm491GP6nyIn5ImeQoYpBHLOsGzQKVsIWHywRx1+WHuzxkxHw4++647Rfx6+bELlhAUEOK+XWOfnaXqqVLkXKVqBFbDcKlCIo+in8v4sGufxPy5bNrSJhJlpuHE23WybGvI4GbWFg8todzPldRpQwPpgEp2f1JW7eNm2vzwVR33QX9KAqueQVawoBHj7yvX2d1Eda4Mhlqc86/6Sf5LWrS/dWAnT6waUe4s4mmzokr7B+OFFVL8BQiHCGdOstTBXtC1Jz0tGYOCdlHjFzNhsWimYtrN7aJras5TzUQrtOo2EJT1/GWBKVffTPM3xNkUmo9y7jfhlDQVCB1yGOCOBiTEoeaWxjmhQ0QkKW8UQp4LC1rrMgB+s9YFu9Au5bYMhQ2fcvH/rdc96K6IMirZ9SmWsDfLaOgMPmQSC4nijY9/YmWDMcC6RrOO+M7Gphgv1zTb2EG

###
GET http://{{hostname}}/nice?popup=&mobile= HTTP/1.1